# Generated by Django 2.2 on 2021-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_connection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
    ]
